
name: Deployment of AWS resources via Terraform

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - task_*

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

env:
  TERRAFORM_VERSION: '1.9.6'
  AWS_GHA_ROLE: 'arn:aws:iam::035511759406:role/GithubActionsRole'
  AWS_REGION: 'us-east-1'

jobs:
  terraform-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check tf_resources/

  terraform-plan:
    runs-on: ubuntu-22.04
    needs: terraform-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_GHA_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform -chdir=tf_resources/ init

      - name: Terraform Plan
        run: terraform -chdir=tf_resources/ plan

  terraform-apply:
    runs-on: ubuntu-22.04
    needs: terraform-plan
    if: github.event_name == 'pull_request' && github.base_ref == 'main' || startsWith(github.ref, 'refs/heads/task_')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_GHA_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform -chdir=tf_resources/ init

      - name: Terraform Apply
        run: terraform -chdir=tf_resources/ apply -auto-approve
