
name: Deployment of AWS resources via Terraform

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - task_1

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Terraform Format Check
        run: terraform fmt -check tf_resources/

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform -chdir=tf_resources/ init

      - name: Terraform Plan
        run: terraform -chdir=tf_resources/ plan

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/task_1'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform -chdir=tf_resources/ init

      - name: Terraform Apply
        run: terraform -chdir=tf_resources/ apply -auto-approve
